In [33]:
import numpy as np 
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from odeintw import odeintw
l=2
M=1
r=0.4
lamb=1
p=1
rho=1
nud=1
nu=1
gamma=1
w=1
pder=1
nu0=1
rho0=1
p0=1
nu2=1
p2=1
rho2=1
nu4=1
p4=1
rho4=1
def chesenki(Y,r) : 
            pi=3.14
            e=2.71828 
            c0= (-1/r)*(l+1+(2*M*(e**lamb)/r)+4*pi*(r**2)*(e**(lamb))*(p-rho))
            c1= (e**lamb)/r
            c2= -16*pi*(rho+p)*(e**lamb)/r
            c3= 1/r
            c4= l*(l+1)/(2*r)
            c5= -(((l+1)/r)-nud/2)
            c6= -8*pi*(rho+p)*(e**(lamb/2))/r
            c7= -(l+1)/r
            c8= (r*(e**(lamb/2))*(e**(-nu/2)))/(p*gamma)
            c9= (-r*(e**(lamb/2))*l*(l+1))/(r**2)
            c10= r*(e**(lamb/2))/2
            c11= 2*c10
            c12= -l/r
            c13= ((rho+p)*((e**(nu/2)))*((1/(2*r))+(-nud/4)))
            c14= ((rho+p)*((e**(nu/2))/2)*(r*(w**2)*(e**(-nu))+(l*(l+1)/(2*r))))
            c15= ((rho+p)*((e**(nu/2))/2)*(3*nud-(1/r)))
            c16= (rho+p)*((e**(nu/2))*((-l)*(l+1)*(nud**2))/(r**2)*2)
            c17= ((rho+p)/r)*((e**(nu/2))*(-4*pi*(rho+p)*(e**(lamb/2))-(w**2)*(e**((lamb/2)-nu))+((r**2)/2)*((e**(-lamb/2))*nud/(r**2))))
            A0= 3*M + (l-1)*(l+2)*r/2 + 4*pi*r*r*pder
            A1= -8*pi*(r**3)*(e**(nu/2))
            A2= (l*(l+1)/2)*(M + 4*pi*(r**3)*p)-(w**2)*(r**3)*(e**(-lamb-nu))
            A3= -((l-1)*(l+2)*r/2-(w**2)*(r**3)*(e**(-nu)) + (e**(lamb)*(4*pi*(r**3)*p)*(3*M-r+4*pi*r)))
            A4= (w**2)*(rho+p)*(e**(-nu/2))
            A5= -(pder/r)*(r**((nu-lamb)/2))
            A6= (e**(nu/2))*(rho+p)/2
            B0= 1 +(A1*A6/A0)
            B1= (A6*A2/A0)
            B2= (A6*A3/A0)
            B3= -A5               
            P0= -(A2*c1/A0)-(B1*c2/A4)
            P1= c1-(c1*A3/A0)-(c2*B2/A4)
            P2= -(c2*B3/A4)
            P3= -(c1*A1/A0)-(c2*B0/A4)
            Q0=(-c3*A2/A0)+c4
            Q1= -(A3*c3/A0) +c5
            Q2= c6
            Q3= -(c3*A1/A0)
            R0= (c9*B1/A4)-(c10*A2/A0)
            R1= (c9*B2/A4)-(c10*A3/A0)+c11
            R2= c7 + (c9*B3/A4)
            R3= c8 + (c9*B0/A4)-(c10*A1/A0)
            S0= c14 + (c16*B1/A4)
            S1= c15 + (c16*B2/A4)
            S2= c17 + (c16*B3/A4)
            S3= c12 + (c16*B0/A4)      
            matrixF=np.matrix([[P0,P1,P2,P3],[Q0,Q1,Q2,Q3],[R0,R1,R2,R3],[S0,S1,S2,S3]])
            #L-D Equation matrices
            #Perturbation Equations
            b1= (-1/r)*(l+1+(2*M*(e**lamb)/r)+4*pi*(r**2)*(e**(lamb))*(p-rho))
            b2= (e**lamb)/r
            b3= -16*pi*(rho+p)*(e**lamb)/r
            b4= 1/r
            b5= l*(l+1)/(2*r)
            b6= -(((l+1)/r)-nud/2)
            b7= -8*pi*(rho+p)*(e**(lamb/2))/r
            b8= -(l+1)/r
            b9= (r*(e**(lamb/2))*(e**(-nu/2)))/(p*gamma)
            b10= (-r*(e**(lamb/2))*l*(l+1))/(r**2)
            b11= r*(e**(lamb/2))/2
            b12= -l/r
            b13= ((rho+p)*((e**(nu/2)))*((1/(2*r))+(-nud/4)))
            b14= ((rho+p)*((e**(nu/2))/2)*(r*(w**2)*(e**(-nu))+(l*(l+1)/(2*r))))
            b15= ((rho+p)*((e**(nu/2))/2)*(3*nud-(1/r)))
            b16= (rho+p)*((e**(nu/2))*((-l)*(l+1)*(nud**2))/(r**2)*2)
            b17= ((rho+p)/r)*((e**(nu/2))*(-4*pi*(rho+p)*(e**(lamb/2))-(w**2)*(e**((lamb/2)-nu))+((r**2)/2)*((e**(-lamb/2))*nud/(r**2))))
            matrixB=np.matrix([[b2,b1,b2,0,b3,0],[b4,b5,b6,b7,0,0],[b11,0,2*b11,b8,b10,b9],[b13,b14,b15,b17,b16,b12]])

            #Direct H0,V equations             
            a1=(w**3)*(p+rho)*(e**(-nu/2))
            a2=-pder*(e**((nu-lamb)/2))/r
            a3=(p+rho)*(e**(nu/2))/2
            e1=3*M+(l+2)*(l-1)*r/2+4*pi*(r**3)*p
            e2=8*pi*(r**3)*(e**(-nu/2))
            e3=(-l*(l+1)*(M+4*pi*(r**3)*p)/2)+((w**2)*(r**3)*(e**(-lamb-nu)))
            e4=((l+2)*(l-1)*r/2)-((w**2)*(r**3)*(e**(-nu)))-((e**lamb)*(M+4*pi*(r**3)*p)*(3*M-r+4*pi*(r**3)*p)/r)    
            matrixE=np.matrix([[e3/e1,e4/e1,0,e2/e1],[(-a3*e3/(a1*e1)),(-a3*e4/(a1*e1)),-a2/a1,((e1-a3*e2)/(a1*e1))]])
            
            #Power Series Analysis matrices
            #Y(0)
            W0=1
            K0=rho0+p0 #value can be positive or negative according to notes
            X0=(p0+rho0)*(e**(nu0/2))*((4*pi*(rho0+3*p0)/3)-((w**2)*(e**(-nu0))/l))*W0+(K0/2)
            H10=(2*l*K0+16*pi*(p0+rho0)*W0)/(l*(l+1))
            matrixY0 = np.matrix([[H10],[K0],[W0],[X0]])
            #Zero value equations
            f1=8*pi*(e**(-nu0/2))*4/((l+2)*(l-1))
            f2=(-4/((l+2)*(l-1)))*((8*pi*p0/3)+((w**2)*(e**(-nu0))))
            f3=(-4/((l+2)*(l-1)))*((2*pi*l*(l+1)*(rho0+3*p0)/3)-(w**2)*(e**(-nu0)))
            f4=2*(e**(-nu0/2))/(l*(l+1)*rho0*p0)
            f5=3/(l*(l+1))
            f6=8*pi*(l+1)*rho0/(3*l*(l+1))
            matrixC=np.matrix([[f3,f2,0,f1],[0,c5,c6,c4]])
            matrixQ0 = np.matmul(matrixC,matrixY0)

            #Equations relating double differentials to zero values
            d1=-(p0+rho0)/4
            d2=(p2+(p0+rho0)*(w**2)*(l+3)*(e**(-nu0))/(l*(l+1)))/2
            d3=(e**(-nu0/2))/2
            d4=nu2*(e**(-nu0/2))/4
            d5=(p2+rho2)/4
            d6=(p0+rho0)/4
            d7=(w**2)*(p0+rho0)*(e**(-nu0))/2
            d8=-p4+(4*pi*rho0*p2)-((w**2)*(e**(-nu0))*(rho2+p2-(rho0+p0)*nu2)/(2*l))
            d9=(l+2)/2
            d10=-l*(l+1)/4
            d11=4*pi*(rho0+p0)
            d12=4*pi*(rho0+3*p0)/3
            d13=1/2
            d14=-4*pi*(rho2+p2+8*pi*rho0*(rho0+p0)/3)
            d15=(l+3)/2
            d16=-8*pi*(p0+rho0)*(l+3)/(l*(l+1))
            d17=4*pi*(((2*l+3)*rho0/3)-p0)
            d18=8*pi*(p2+rho2)/l
            d19=-8*pi*(rho0+p0)
            d20=1/2
            d21=(l+1)/2
            d22=-l*(l+1)*(rho0+p0)*(e**(nu0/2))/8
            d23=-(rho0+p0)*(e**(nu0/2))*(((l+2)*nu2/4)-2*pi*(rho0+p0)-((w**2)*(e**(-nu0))/2))
            d24=l*(rho2+p2+(nu2*(rho0+p0)/2))/(2*(rho0+p0))
            d25=(p0+rho0)*(e**(nu0/2))*nu2/2
            d26=(p0+rho0)*(e**(nu0/2))/4
            d27=(p0+rho0)*(e**(-nu0/2))*(w**2)/2
            d28=-(p0+rho0)*(e**(nu0/2))*l*(l+1)*nu2/4
            d29=(p0+rho0)*(e**(nu0/2))*((l+1)*nu4/2-2*pi*(rho2+p2)-16*(pi**2)*rho0*(rho0+p0)/3+(nu4-(4*pi*rho0*nu2/3))/2+(w**2)*(e**(-nu0))*(nu2-8*pi*rho0/3)/2)
            d30=-1
             
            #Taylor
            matrixYQ0 = np.vstack([matrixY0,matrixQ0])
            matrixT = np.matrix([[0,d1,d2,d3],[d10,d9,d11,0],[d15,d30,d16,0],[d22,0,d23,d21]])
            matrixU = np.matrix([[0,d5,d8,d4,d6,d7],[0,d12,d14,0,d13,0],[d17,0,d18,0,d19,d20],[d27,d25,d29,d24,d26,d28]])
            matrixTinv = np.linalg.inv(matrixT)
            matrixY = np.add(matrixY0,((r**2)*0.5*np.matmul(np.matmul(matrixTinv,matrixU),matrixYQ0)))
            #print(matrixY)
            H1=matrixY.item(0)
            K=matrixY.item(1)
            W=matrixY.item(2)
            X=matrixY.item(3)
            H0=(e3/e1)*H1 + (e4/e1)*K + (e2/e1)*X
            V= -((a3*e3)/(a1*e1))*H1 -((a3*e4)/(a1*e1))*K-((a2)/(a1))*W-((e1-(a3*e2))/(e1))*X
            #Defining the original six vector
            matrixA=np.matrix([[H0],[H1],[K],[W],[V],[X]])  
            #Defining the transformed four vector
            Y=np.matrix([[H1],[K],[W],[X]])
            #B=np.matrix([[H0],[V]])
            #B=np.matmul(matrixE,Y)
            
            dYdr=np.matmul(matrixB,matrixA)
    
        
            return dYdr 
Ytest=np.array([[-58.68675554],[123.77004882],[-14.03024504],[294.03981581]])
t=np.linspace(0.4,10.4,1000)
Y=odeintw(chesenki,Ytest,t)
print(Y)

[[[-5.86867555e+01]
  [ 1.23770049e+02]
  [-1.40302450e+01]
  [ 2.94039816e+02]]

 [[-1.16048669e+04]
  [ 9.60709003e+01]
  [-4.28992864e+02]
  [-3.81339835e+03]]

 [[-2.34914526e+04]
  [ 6.80873549e+01]
  [-8.56465164e+02]
  [-7.94126213e+03]]

 ...

 [[-2.80269137e+10]
  [-7.44376271e+07]
  [-5.43450964e+09]
  [-1.27223446e+08]]

 [[-2.81353648e+10]
  [-7.47265041e+07]
  [-5.46413610e+09]
  [-1.26721717e+08]]

 [[-2.82441302e+10]
  [-7.50162201e+07]
  [-5.49389828e+09]
  [-1.26214687e+08]]]
